version: "3.8"

services:
  redis:
    image: redis:6-alpine
    container_name: mefo-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  fastapi:
    build: .
    container_name: mefo-ai
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    healthcheck:
      test: ["CMD","curl","-f","http://fastapi:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data: